### ISSUE TITLE
Docx report do not render (3.2.0)

### ISSUE THREAD

**Issue by Gaetan-IRSN** [biodosimetry-uab/biodosetools#12]
### Bug report/feedback

- Assessment: Dicentrics: Dose-effect fitting
- Module: Export Results

When selecting .docx as export format for Report, the generation of the report fails
R console output:

> processing file: dicentrics-report.Rmd
>   |......                                                                                                            |   5%
>    inline R code fragments
> 
>   |............                                                                                                      |  11%
> label: unnamed-chunk-1 (with options) 
> List of 1
>  $ include: logi FALSE
> 
> Quitting from lines 11-12 (dicentrics-report.Rmd) 
> 
> Warning: Error in loadNamespace: aucun package nommé 'pander' n'est trouvé
>   [No stack trace available]

Workthrough :
Installation of pander package solves the issue

Proposed correction: 
To add pander package in the list of required packages 

Describe what issue or problem you are experiencing on the application.

**Please attach an image if it helps to visualize the problem.**

**Comment by aldomann** [comment]
The `pander` package needs to be added to the list of imported packages on the `DESCRIPTION` file. The package build/check process only checks for requirements in the actual package functions, not on the Shiny; so I definitely forgot to manually check the reports for additional packages.

For now, the manual solution is to install `pander` on your own:
```r
install.packages("pander")
```

**Comment by aldomann** [comment]
Fixed in 52a41de6ed8ccdcfff0eff2fd9d1077a167cd693
