### ISSUE TITLE
Small confidence intervals in underdispersed data (Delta Method)

### ISSUE THREAD

**Issue by aldomann** [biodosimetry-uab/biodosetools#7]
### Bug report/feedback (from David)

- Assessment: Dicentrics
- Module: Dose estimation

For the delta method you always use the empirical standard error of the dicentric counts for the estimation of confidence intervals. I would recommend that you use at least the Poisson error if dispersion < 1 and the empirical standard error otherwise. Otherwise you sometimes get really small CI’s if the data is underdispersed.

For `disp < 1` you can use
 
```r
se.Y <- sqrt(number dics)/(number cells)
```

For `disp >= 1` keep it as it is at the moment.

**Comment by aldomann** [comment]
@dendesfelder Would this also apply for translocations and micronuclei? Or should we only use the empirical error for them?

**Comment by aldomann** [comment]
I'm trying this implementation at the moment:

```r
disp <- case_data[["DI"]]

if (disp >= 1) {
  # Use empirical error sqrt(var / N) if disp >= 1
  if (aberr_module == "dicentrics" | aberr_module == "micronuclei") {
    lambda_est_sd <- case_data[["y_err"]]
  } else if (aberr_module == "translocations") {
    lambda_est_sd <- case_data[["Fg_err"]]
  }
} else {
  # Use Poisson error if disp < 1
  lambda_est_sd <- sqrt(case_data[["X"]]) / case_data[["N"]]
}
```

Would these results make sense? Using `C0=5`, and `C1=2` and the fitting curve from IAEA:

| Before fix | After fix |
|-----------|---------|
| ![image](https://user-images.githubusercontent.com/729732/74645231-6ec75b80-516f-11ea-8f65-6676d26f329b.png) | ![image](https://user-images.githubusercontent.com/729732/74645329-974f5580-516f-11ea-9a0a-7a3bf03e47b8.png) |

**Comment by dendesfelder** [comment]
Seems to make sense. Which calibration curve coefficients did you use for dose estimation. I would say that the same applies for translocations and Micronuclei, too. For very high doses of low-LET we would expect some degree of underdispersion and we might therefore slightly overestimate the uncertainty with this approach. However, I believe it's better to overestimate than underestimate.
